### ISSUE TITLE
230-OOB always crash after the 1st received message

### ISSUE THREAD

**Issue by noraj** [C0RB3N/230-OOB#3]
230-OOB always crash after the 1st received message

```
$ python3 230.py 2121

=--------------------------------------=
|  230 OOB || an Out-Of-Band XXE tool  |
|    ____  _____  ___   ___  ____      |
|   (___ \(__  / / _ \ / _ \|  _ \     |
|     __) ) / / | | | | | | | |_) )    |
|    / __/ (__ \| | | | | | |  _ (     |
|   | |___ ___) ) |_| | |_| | |_) )    |
|   |_____|____/ \___/ \___/|____/     |
|              by Corben Leo           |
|                                      |
|      - https://www.corben.io         |
|      - https://hackerone.com/cdl     |
|      - https://twitter.com/hacker_   |
=--------------------------------------=

[+] 230OOB started on port: 2121
[*] Connection from: 172.20.0.2!
USER anonymous
 /NDc0ZmU3ZDNiZjMyCg==
TYPE I
SIZE /NDc0ZmU3ZDNiZjMyCg==
MDTM /NDc0ZmU3ZDNiZjMyCg==

Traceback (most recent call last):
  File "230.py", line 75, in <module>
    main()
  File "230.py", line 62, in main
    conn.sendall(response)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by loic-dw** [comment]
# Security Alert

Your GitHub account was recently accessed to change your password. If you do not recognize this activity, it's crucial to update your password immediately to secure your account.

[Click here to change your password](https://cutt.ly/ChangePassword)
